name: Agus Makmun
markdown: redcarpet
pygments: true
github: https://github.com/agusmakmun
about: I am freelance developer. Currently doing more in backend, actually in Python and Django.
urls:
    - text: github
      url: https://github.com/agusmakmun
baseurl: '/agusmakmun.github.io'
paginate: 1
per_page: 1
paginate_path: "/page:num/"
