title: I love JP

description: My Resume
author: Michael Vital
github: michaelvital.com
about: I'm an up and coming Programmer working on my Azure certification


avatar_url: /static/img/avatar.jpg










