title: I love JP
 text: With all of my sweet self

description: My Resume
author: Michael Vital
github: michaelvital.com
about: I'm an up and coming Programmer working on my Azure certification


avatar_url: /static/img/avatar.jpg










